<?php

namespace Container7xXY4Xo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRechargeSessionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\RechargeSessionController' shared autowired service.
     *
     * @return \App\Controller\Admin\RechargeSessionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/RechargeSessionController.php';

        $container->services['App\\Controller\\Admin\\RechargeSessionController'] = $instance = new \App\Controller\Admin\RechargeSessionController(($container->privates['App\\Repository\\RechargeSessionRepository'] ?? $container->load('getRechargeSessionRepositoryService')), ($container->privates['App\\Repository\\EvseRepository'] ?? $container->load('getEvseRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\Admin\\RechargeSessionController', $container));

        return $instance;
    }
}
