<?php

namespace Container7xXY4Xo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSessionFilterFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AdminSessionFilterForm' shared autowired service.
     *
     * @return \App\Form\AdminSessionFilterForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AdminSessionFilterForm.php';

        return $container->privates['App\\Form\\AdminSessionFilterForm'] = new \App\Form\AdminSessionFilterForm();
    }
}
