<?php

namespace Container7xXY4Xo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateConnectorCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateConnectorCommand' shared autowired service.
     *
     * @return \App\Command\CreateConnectorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateConnectorCommand.php';

        $container->privates['App\\Command\\CreateConnectorCommand'] = $instance = new \App\Command\CreateConnectorCommand(($container->privates['App\\Repository\\ConnectorRepository'] ?? $container->load('getConnectorRepositoryService')));

        $instance->setName('app:create-connector');

        return $instance;
    }
}
