<?php

namespace Container7xXY4Xo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\EvseController' shared autowired service.
     *
     * @return \App\Controller\Admin\EvseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/EvseController.php';

        $container->services['App\\Controller\\Admin\\EvseController'] = $instance = new \App\Controller\Admin\EvseController(($container->privates['App\\Repository\\EvseRepository'] ?? $container->load('getEvseRepositoryService')), ($container->privates['App\\Repository\\StationRepository'] ?? $container->load('getStationRepositoryService')), ($container->privates['App\\Repository\\ConnectorRepository'] ?? $container->load('getConnectorRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\Admin\\EvseController', $container));

        return $instance;
    }
}
