<?php

namespace Container7xXY4Xo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStationController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StationController' shared autowired service.
     *
     * @return \App\Controller\StationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StationController.php';

        $container->services['App\\Controller\\StationController'] = $instance = new \App\Controller\StationController(($container->privates['App\\Repository\\StationRepository'] ?? $container->load('getStationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\StationController', $container));

        return $instance;
    }
}
