<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTN90IYj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTN90IYj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTN90IYj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTN90IYj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTN90IYj\App_KernelDevDebugContainer([
    'container.build_hash' => 'TN90IYj',
    'container.build_id' => 'e3dba824',
    'container.build_time' => 1728292151,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTN90IYj');
